class CuplistsController < ApplicationController
  # GET /idollists
  # GET /idollists.json
  def index
    @a_acuplists = AIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @a_bcuplists = AIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @a_ccuplists = AIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @a_dcuplists = AIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @a_ecuplists = AIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @a_fcuplists = AIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @a_gcuplists = AIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @a_hcuplists = AIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @a_icuplists = AIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @a_jcuplists = AIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @a_kcuplists = AIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @a_lcuplists = AIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ka_acuplists = KaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ka_bcuplists = KaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ka_ccuplists = KaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ka_dcuplists = KaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ka_ecuplists = KaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ka_fcuplists = KaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ka_gcuplists = KaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ka_hcuplists = KaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ka_icuplists = KaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ka_jcuplists = KaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ka_kcuplists = KaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ka_lcuplists = KaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @sa_acuplists = SaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @sa_bcuplists = SaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @sa_ccuplists = SaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @sa_dcuplists = SaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @sa_ecuplists = SaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @sa_fcuplists = SaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @sa_gcuplists = SaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @sa_hcuplists = SaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @sa_icuplists = SaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @sa_jcuplists = SaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @sa_kcuplists = SaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @sa_lcuplists = SaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ta_acuplists = TaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ta_bcuplists = TaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ta_ccuplists = TaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ta_dcuplists = TaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ta_ecuplists = TaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ta_fcuplists = TaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ta_gcuplists = TaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ta_hcuplists = TaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ta_icuplists = TaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ta_jcuplists = TaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ta_kcuplists = TaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ta_lcuplists = TaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @na_acuplists = NaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @na_bcuplists = NaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @na_ccuplists = NaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @na_dcuplists = NaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @na_ecuplists = NaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @na_fcuplists = NaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @na_gcuplists = NaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @na_hcuplists = NaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @na_icuplists = NaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @na_jcuplists = NaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @na_kcuplists = NaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @na_lcuplists = NaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ha_acuplists = HaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ha_bcuplists = HaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ha_ccuplists = HaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ha_dcuplists = HaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ha_ecuplists = HaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ha_fcuplists = HaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ha_gcuplists = HaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ha_hcuplists = HaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ha_icuplists = HaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ha_jcuplists = HaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ha_kcuplists = HaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ha_lcuplists = HaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ma_acuplists = MaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ma_bcuplists = MaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ma_ccuplists = MaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ma_dcuplists = MaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ma_ecuplists = MaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ma_fcuplists = MaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ma_gcuplists = MaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ma_hcuplists = MaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ma_icuplists = MaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ma_jcuplists = MaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ma_kcuplists = MaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ma_lcuplists = MaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ya_acuplists = YaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ya_bcuplists = YaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ya_ccuplists = YaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ya_dcuplists = YaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ya_ecuplists = YaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ya_fcuplists = YaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ya_gcuplists = YaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ya_hcuplists = YaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ya_icuplists = YaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ya_jcuplists = YaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ya_kcuplists = YaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ya_lcuplists = YaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @ra_acuplists = RaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @ra_bcuplists = RaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @ra_ccuplists = RaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @ra_dcuplists = RaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @ra_ecuplists = RaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @ra_fcuplists = RaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @ra_gcuplists = RaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @ra_hcuplists = RaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @ra_icuplists = RaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @ra_jcuplists = RaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @ra_kcuplists = RaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @ra_lcuplists = RaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)

    @wa_acuplists = WaIdollist.where(cup: 'A').order(:family_name_kana, :given_name_kana)
    @wa_bcuplists = WaIdollist.where(cup: 'B').order(:family_name_kana, :given_name_kana)
    @wa_ccuplists = WaIdollist.where(cup: 'C').order(:family_name_kana, :given_name_kana)
    @wa_dcuplists = WaIdollist.where(cup: 'D').order(:family_name_kana, :given_name_kana)
    @wa_ecuplists = WaIdollist.where(cup: 'E').order(:family_name_kana, :given_name_kana)
    @wa_fcuplists = WaIdollist.where(cup: 'F').order(:family_name_kana, :given_name_kana)
    @wa_gcuplists = WaIdollist.where(cup: 'G').order(:family_name_kana, :given_name_kana)
    @wa_hcuplists = WaIdollist.where(cup: 'H').order(:family_name_kana, :given_name_kana)
    @wa_icuplists = WaIdollist.where(cup: 'I').order(:family_name_kana, :given_name_kana)
    @wa_jcuplists = WaIdollist.where(cup: 'J').order(:family_name_kana, :given_name_kana)
    @wa_kcuplists = WaIdollist.where(cup: 'K').order(:family_name_kana, :given_name_kana)
    @wa_lcuplists = WaIdollist.where(cup: 'L').order(:family_name_kana, :given_name_kana)
  end
end
